---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-mysql-cnmsql-io-v1alpha1-cluster-status
  failurePolicy: Fail
  name: vclusterstatus-v1alpha1.cnmsql.co
  rules:
  - apiGroups:
    - mysql.cnmsql.co
    apiVersions:
    - v1alpha1
    operations:
    - UPDATE
    resources:
    - clusters
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-mysql-cnmsql-io-v1alpha1-cluster-spec
  failurePolicy: Fail
  name: vclustervalidation-v1alpha1.cnmsql.co
  rules:
  - apiGroups:
    - mysql.cnmsql.co
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - clusters
  sideEffects: None
