## Append samples of your project ##
resources:
- mysql_v1alpha1_cluster.yaml
- mysql_v1alpha1_backup.yaml
- mysql_v1alpha1_scheduledbackup.yaml
- mysql_v1alpha1_database.yaml
- mysql_v1alpha1_imagecatalog.yaml
- mysql_v1alpha1_clusterimagecatalog.yaml
# +kubebuilder:scaffold:manifestskustomizesamples
