apiVersion: mysql.cloudnative-mysql.io/v1alpha1
kind: Database
metadata:
  labels:
    app.kubernetes.io/name: cloudnative-mysql
    app.kubernetes.io/managed-by: kustomize
  name: testdb
spec:
  cluster:
    name: cluster-sample
  reclaimPolicy: delete
  users:
  - name: testdb
    passwordSecret:
      name: testdb-user
      key: password
    grants:
    - privileges:
      - ALL
