apiVersion: mysql.cnmsql.co/v1alpha1
kind: ImageCatalog
metadata:
  labels:
    app.kubernetes.io/name: cnmsql
    app.kubernetes.io/managed-by: kustomize
  name: imagecatalog-sample
spec:
  images:
  - series: "8.0"
    image: percona/percona-server:8.0
  - series: "8.4"
    image: percona/percona-server:8.4
  - series: "9.0"
    image: percona/percona-server:9.0
