apiVersion: mysql.cloudnative-mysql.io/v1alpha1
kind: Cluster
metadata:
  labels:
    app.kubernetes.io/name: cnmysql
    app.kubernetes.io/managed-by: kustomize
  name: cluster-sample
spec:
  instances: 1
  imageName: cnmysql-instance:8.0
  storage:
    size: 10Gi
  mysql:
    binlogFormat: ROW
  bootstrap:
    initdb:
      database: app
      owner: app
