apiVersion: mysql.cnmsql.co/v1alpha1
kind: Cluster
metadata:
  labels:
    app.kubernetes.io/name: cnmsql
    app.kubernetes.io/managed-by: kustomize
  name: cluster-sample
spec:
  instances: 3
  imageName: ghcr.io/cnmsql/cnmsql-instance:8.4
  storage:
    size: 10Gi
  mysql:
    binlogFormat: ROW
  bootstrap:
    initdb:
      database: app
      owner: app
