/*
Copyright 2026 The CloudNative MySQL Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package config

import (
	"strings"
	"testing"
)

func baseConfig() *ServerConfig {
	return &ServerConfig{
		ServerID:     1,
		Version:      "8.0.36",
		Role:         RolePrimary,
		DataDir:      "/var/lib/mysql",
		Socket:       "/var/run/mysqld/mysqld.sock",
		BinlogFormat: "ROW",
	}
}

func mustRender(t *testing.T, c *ServerConfig) string {
	t.Helper()
	out, err := c.Render()
	if err != nil {
		t.Fatalf("Render() unexpected error: %v", err)
	}
	return out
}

func assertContains(t *testing.T, haystack, needle string) {
	t.Helper()
	if !strings.Contains(haystack, needle) {
		t.Errorf("expected rendered config to contain %q\n---\n%s", needle, haystack)
	}
}

func assertNotContains(t *testing.T, haystack, needle string) {
	t.Helper()
	if strings.Contains(haystack, needle) {
		t.Errorf("expected rendered config NOT to contain %q\n---\n%s", needle, haystack)
	}
}

func TestRenderPrimaryBaseline(t *testing.T) {
	out := mustRender(t, baseConfig())

	assertContains(t, out, "[mysqld]")
	assertContains(t, out, "server-id = 1")
	assertContains(t, out, "gtid_mode = ON")
	assertContains(t, out, "enforce_gtid_consistency = ON")
	assertContains(t, out, "binlog_format = ROW")
	assertContains(t, out, "log_bin = binlog")
	// A primary's rendered config is not read-only (the run container boots
	// read-only via a mysqld flag instead, cleared by the in-Pod reconciler).
	assertNotContains(t, out, "read_only")
	assertNotContains(t, out, "super_read_only")
}

func TestRenderArchivingDisabled(t *testing.T) {
	out := mustRender(t, baseConfig())
	assertNotContains(t, out, "sync_binlog")
	assertNotContains(t, out, "max_binlog_size")
	assertNotContains(t, out, "binlog_expire_logs_seconds")
}

func TestRenderArchivingEnabled(t *testing.T) {
	c := baseConfig()
	c.Archiving = Archiving{Enabled: true, MaxBinlogSizeMB: 16, BinlogExpireSeconds: 604800}
	out := mustRender(t, c)
	assertContains(t, out, "sync_binlog = 1")
	assertContains(t, out, "max_binlog_size = 16777216")
	assertContains(t, out, "binlog_expire_logs_seconds = 604800")
}

func TestRenderArchivingLegacyExpiry(t *testing.T) {
	c := baseConfig()
	c.Version = "5.7.44"
	c.Archiving = Archiving{Enabled: true, BinlogExpireSeconds: 604800}
	out := mustRender(t, c)
	// 604800s = 7 days on a server without binlog_expire_logs_seconds.
	assertContains(t, out, "expire_logs_days = 7")
	assertNotContains(t, out, "binlog_expire_logs_seconds")
}

func TestArchivingKeysAreManaged(t *testing.T) {
	c := baseConfig()
	c.UserParameters = map[string]string{"sync_binlog": "0"}
	if _, err := c.Render(); err == nil {
		t.Fatal("expected sync_binlog to be rejected as managed")
	}
}

func TestStripGroupReplicationRemovesGRBlock(t *testing.T) {
	in := strings.Join([]string{
		"# Generated by cloudnative-mysql instance manager. Do not edit.",
		"[mysqld]",
		"server-id = 1",
		"gtid_mode = ON",
		"plugin_load_add = group_replication.so",
		"group_replication_group_name = 5d776d90-1ba6-4f3a-9027-f82fbb25e393",
		"group-replication-local-address = host:33061",
		"# --- user-provided ---",
		"max_connections = 100",
		"",
	}, "\n")

	out := StripGroupReplication(in)

	for _, gone := range []string{"plugin_load_add", "group_replication_group_name", "group-replication-local-address"} {
		if strings.Contains(out, gone) {
			t.Errorf("expected %q to be stripped, got:\n%s", gone, out)
		}
	}
	// Non-GR settings, comments and the section header must survive.
	for _, kept := range []string{
		"[mysqld]", "server-id = 1", "gtid_mode = ON", "max_connections = 100", "# --- user-provided ---",
	} {
		if !strings.Contains(out, kept) {
			t.Errorf("expected %q to be kept, got:\n%s", kept, out)
		}
	}
}

func TestStrippedConfigInitializesWhereFullConfigWouldAbort(t *testing.T) {
	// A rendered GR config must be parseable by `mysqld --initialize`, which
	// ignores plugin_load_add and would otherwise reject group_replication_* as
	// unknown variables. The stripped copy must carry no GR keys.
	c := baseConfig()
	c.TopologyMode = TopologyGroupReplication
	c.GroupReplication = GroupReplication{
		GroupName:    "5d776d90-1ba6-4f3a-9027-f82fbb25e393",
		LocalAddress: "host:33061",
		GroupSeeds:   "host:33061",
	}
	full := mustRender(t, c)
	if !strings.Contains(full, "group_replication_group_name") {
		t.Fatal("precondition: rendered GR config should contain the GR block")
	}

	stripped := StripGroupReplication(full)
	for line := range strings.SplitSeq(stripped, "\n") {
		trimmed := strings.TrimSpace(line)
		if trimmed == "" || strings.HasPrefix(trimmed, "#") || strings.HasPrefix(trimmed, "[") {
			continue
		}
		key := trimmed
		if before, _, ok := strings.Cut(trimmed, "="); ok {
			key = before
		}
		if IsDeniedKey(key) && (strings.HasPrefix(normalizeKey(key), "group_replication_") ||
			normalizeKey(key) == "plugin_load_add") {
			t.Errorf("stripped config still carries GR key %q", key)
		}
	}
}

func TestRenderReplicaIsReadOnly(t *testing.T) {
	c := baseConfig()
	c.Role = RoleReplica
	out := mustRender(t, c)

	assertContains(t, out, "read_only = ON")
	assertContains(t, out, "super_read_only = ON")
}

func TestRenderVersionAwareLogUpdates(t *testing.T) {
	c := baseConfig()
	c.Version = "8.0.36"
	assertContains(t, mustRender(t, c), "log_replica_updates = ON")
	assertNotContains(t, mustRender(t, c), "log_slave_updates")

	c.Version = "5.7.44"
	assertContains(t, mustRender(t, c), "log_slave_updates = ON")
	assertNotContains(t, mustRender(t, c), "log_replica_updates")
}

func TestRenderReplicaBeforeSuperReadOnlyHasNoSuperReadOnly(t *testing.T) {
	c := baseConfig()
	c.Version = "5.7.7"
	c.Role = RoleReplica
	out := mustRender(t, c)

	assertContains(t, out, "read_only = ON")
	assertNotContains(t, out, "super_read_only")
}

func TestRenderTLSConfiguresMaterialWithoutForcingSecureTransport(t *testing.T) {
	c := baseConfig()
	c.TLS = TLSPaths{CA: "/tls/ca.crt", Cert: "/tls/tls.crt", Key: "/tls/tls.key"}
	out := mustRender(t, c)

	assertContains(t, out, "ssl_ca = /tls/ca.crt")
	assertContains(t, out, "ssl_cert = /tls/tls.crt")
	assertContains(t, out, "ssl_key = /tls/tls.key")
	// require_secure_transport is the user's choice, not forced by the operator.
	assertNotContains(t, out, "require_secure_transport")
}

func TestUserCanRequireSecureTransport(t *testing.T) {
	c := baseConfig()
	c.UserParameters = map[string]string{"require_secure_transport": "ON"}
	if err := ValidateUserParameters(c.UserParameters); err != nil {
		t.Fatalf("require_secure_transport should be user-settable: %v", err)
	}
	out := mustRender(t, c)
	assertContains(t, out, "require_secure_transport = ON")
}

func TestRenderSemiSync(t *testing.T) {
	c := baseConfig()
	c.SemiSync = SemiSync{Enabled: true, WaitForReplicaCount: 1, TimeoutMillis: 5000}
	out := mustRender(t, c)

	assertContains(t, out, "loose-rpl_semi_sync_source_enabled = 1")
	assertContains(t, out, "loose-rpl_semi_sync_replica_enabled = 1")
	assertContains(t, out, "loose-rpl_semi_sync_source_wait_for_replica_count = 1")
	assertContains(t, out, "loose-rpl_semi_sync_source_timeout = 5000")
}

func TestRenderAdminInterfaceModern(t *testing.T) {
	c := baseConfig()
	c.Version = "8.0.36"
	out := mustRender(t, c)

	assertContains(t, out, "admin_address = 127.0.0.1")
	assertContains(t, out, "admin_port = 33062")
}

func TestRenderAdminInterfaceCustom(t *testing.T) {
	c := baseConfig()
	c.Version = "8.4.0"
	c.AdminAddress = "127.0.0.2"
	c.AdminPort = 40000
	out := mustRender(t, c)

	assertContains(t, out, "admin_address = 127.0.0.2")
	assertContains(t, out, "admin_port = 40000")
}

func TestRenderAdminInterfaceUnsupportedVersions(t *testing.T) {
	for _, ver := range []string{"5.7.44", "8.0.13"} {
		c := baseConfig()
		c.Version = ver
		out := mustRender(t, c)
		assertNotContains(t, out, "admin_address")
		assertNotContains(t, out, "admin_port")
	}
}

func TestRenderRejectsAdminInterfaceUserParameters(t *testing.T) {
	for _, key := range []string{"admin_address", "admin-port"} {
		c := baseConfig()
		c.UserParameters = map[string]string{key: "x"}
		if _, err := c.Render(); err == nil {
			t.Errorf("expected Render() to reject managed parameter %q", key)
		}
	}
}

func TestRenderUserParametersAppended(t *testing.T) {
	c := baseConfig()
	c.UserParameters = map[string]string{
		"max_connections":         "500",
		"innodb_buffer_pool_size": "2G",
	}
	out := mustRender(t, c)

	assertContains(t, out, "max_connections = 500")
	assertContains(t, out, "innodb_buffer_pool_size = 2G")
	assertContains(t, out, "# --- user-provided ---")
}

func TestRenderRejectsManagedUserParameters(t *testing.T) {
	managedAttempts := []string{
		"server-id", "server_id", "gtid_mode", "gtid-mode",
		"log_bin", "super_read_only", "binlog_format", "SSL_CA",
	}
	for _, key := range managedAttempts {
		c := baseConfig()
		c.UserParameters = map[string]string{key: "whatever"}
		if _, err := c.Render(); err == nil {
			t.Errorf("expected Render() to reject managed parameter %q", key)
		}
	}
}

func TestRenderRejectsInvalidServerID(t *testing.T) {
	c := baseConfig()
	c.ServerID = 0
	if _, err := c.Render(); err == nil {
		t.Error("expected Render() to reject serverID 0")
	}
}

func TestRenderRejectsInvalidRoleAndVersion(t *testing.T) {
	c := baseConfig()
	c.Role = "leader"
	if _, err := c.Render(); err == nil {
		t.Error("expected Render() to reject invalid role")
	}

	c = baseConfig()
	c.Version = "not-a-version"
	if _, err := c.Render(); err == nil {
		t.Error("expected Render() to reject invalid version")
	}
}

func TestValidateUserParametersRejectsDeniedKeys(t *testing.T) {
	deniedAttempts := []string{
		"datadir", "tmpdir", "plugin_dir", "secure_file_priv",
		"admin_ssl_cert", "tls_ciphersuites",
		"log-error", "PORT", "skip_replica_start",
	}
	for _, key := range deniedAttempts {
		if !IsDeniedKey(key) {
			t.Errorf("IsDeniedKey(%q) = false, want true", key)
		}
		c := baseConfig()
		c.UserParameters = map[string]string{key: "x"}
		if _, err := c.Render(); err == nil {
			t.Errorf("expected Render() to reject denied parameter %q", key)
		}
	}
}

func TestDeprecatedUserParameters(t *testing.T) {
	warnings := DeprecatedUserParameters(map[string]string{
		"master_info_repository": "TABLE",
		"max_connections":        "100",
		"slave_parallel_workers": "4",
	})
	if len(warnings) != 2 {
		t.Fatalf("warnings = %v, want 2", warnings)
	}
	joined := strings.Join(warnings, "|")
	if !strings.Contains(joined, "master_info_repository") || !strings.Contains(joined, "slave_parallel_workers") {
		t.Errorf("missing expected deprecation warnings, got: %v", warnings)
	}
	if strings.Contains(joined, "max_connections") {
		t.Errorf("non-deprecated key should not warn, got: %v", warnings)
	}
}

func TestValidateUserParametersListsAllConflicts(t *testing.T) {
	err := ValidateUserParameters(map[string]string{
		"server-id":       "5",
		"gtid_mode":       "OFF",
		"max_connections": "100",
	})
	if err == nil {
		t.Fatal("expected an error")
	}
	if !strings.Contains(err.Error(), "server-id") || !strings.Contains(err.Error(), "gtid_mode") {
		t.Errorf("error should list both conflicts, got: %v", err)
	}
	if strings.Contains(err.Error(), "max_connections") {
		t.Errorf("error should not list the valid parameter, got: %v", err)
	}
}

func grConfig() *ServerConfig {
	c := baseConfig()
	c.TopologyMode = TopologyGroupReplication
	c.GroupReplication = GroupReplication{
		GroupName:       "aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa",
		LocalAddress:    "cluster-1.cluster.svc:33061",
		GroupSeeds:      "cluster-1.cluster.svc:33061,cluster-2.cluster.svc:33061",
		IPAllowlist:     "10.0.0.0/8",
		Consistency:     "BEFORE_ON_PRIMARY_FAILOVER",
		ExitStateAction: "READ_ONLY",
		AutoRejoinTries: 3,
		RecoverySSL:     TLSPaths{CA: "/tls/ca.crt", Cert: "/tls/tls.crt", Key: "/tls/tls.key"},
	}
	return c
}

func TestRenderAsyncOmitsGroupReplication(t *testing.T) {
	// The default (async) topology renders none of the group_replication_* block.
	out := mustRender(t, baseConfig())
	assertNotContains(t, out, "group_replication_")
	assertNotContains(t, out, "plugin_load_add")
}

func TestRenderGroupReplicationBlock(t *testing.T) {
	out := mustRender(t, grConfig())

	assertContains(t, out, "plugin_load_add = group_replication.so")
	assertContains(t, out, "group_replication_group_name = aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa")
	assertContains(t, out, "group_replication_local_address = cluster-1.cluster.svc:33061")
	assertContains(t, out, "group_replication_group_seeds = cluster-1.cluster.svc:33061,cluster-2.cluster.svc:33061")
	assertContains(t, out, "group_replication_single_primary_mode = ON")
	assertContains(t, out, "group_replication_enforce_update_everywhere_checks = OFF")
	assertContains(t, out, "group_replication_consistency = BEFORE_ON_PRIMARY_FAILOVER")
	assertContains(t, out, "group_replication_exit_state_action = READ_ONLY")
	assertContains(t, out, "group_replication_autorejoin_tries = 3")
	assertContains(t, out, "group_replication_ssl_mode = REQUIRED")
	assertContains(t, out, "group_replication_recovery_use_ssl = ON")
	assertContains(t, out, "group_replication_recovery_ssl_ca = /tls/ca.crt")
	assertContains(t, out, "group_replication_ip_allowlist = 10.0.0.0/8")
}

func TestRenderGroupReplicationLoadsClonePlugin(t *testing.T) {
	// Clone-plugin distributed recovery is available from 8.0.17, so the joiner can
	// recover a full snapshot when binlog catch-up is impossible. The operator only
	// loads the plugin and leaves group_replication_clone_threshold at its default
	// (binlog-first, clone-on-gap).
	c := grConfig()
	c.Version = "8.0.22"
	out := mustRender(t, c)
	assertContains(t, out, "plugin_load_add = mysql_clone.so")
	assertNotContains(t, out, "group_replication_clone_threshold")
}

func TestRenderGroupReplicationOmitsClonePluginBelowFloor(t *testing.T) {
	// Below 8.0.17 the clone plugin is unavailable; distributed recovery falls back
	// to binlog catch-up only. (The GR floor is 8.0.22, so this only guards the
	// rendering branch.)
	c := grConfig()
	c.Version = "8.0.16"
	assertNotContains(t, mustRender(t, c), "mysql_clone.so")
}

func TestRenderGroupReplicationNeverBootstrapsOrStartsOnBoot(t *testing.T) {
	// The two split-brain-critical defaults: the operator controls start, and
	// bootstrap is never a config-file default (it would re-bootstrap each boot).
	out := mustRender(t, grConfig())
	assertContains(t, out, "group_replication_start_on_boot = OFF")
	assertContains(t, out, "group_replication_bootstrap_group = OFF")
	assertNotContains(t, out, "group_replication_bootstrap_group = ON")
}

func TestRenderGroupReplicationBinlogChecksumVersionBranch(t *testing.T) {
	// Before 8.0.21 GR requires binlog_checksum=NONE; 8.0.21+ tolerate the default.
	c := grConfig()
	c.Version = "8.0.22"
	assertNotContains(t, mustRender(t, c), "binlog_checksum")

	c.Version = "8.0.20"
	assertContains(t, mustRender(t, c), "binlog_checksum = NONE")
}

func TestGroupReplicationKeysAreManaged(t *testing.T) {
	for _, key := range []string{
		"group_replication_group_name",
		"group-replication-single-primary-mode",
		"plugin_load_add",
	} {
		c := baseConfig()
		c.UserParameters = map[string]string{key: "x"}
		if _, err := c.Render(); err == nil {
			t.Errorf("expected Render() to reject managed group-replication key %q", key)
		}
		if !IsDeniedKey(key) {
			t.Errorf("expected %q to be reported as a denied key", key)
		}
	}
}
