{{- define "gvList" -}}
{{- $groupVersions := . -}}
---
title: "API Reference"
description: "Field reference for every CNMSQL - CloudNative for MySQL CRD, generated from the Go API types."
sidebar_position: 15
toc_max_heading_level: 4
---

{/* Generated by `make api-docs` from api/ with config/crd-ref-docs. Do not edit by hand. */}

# API Reference

This page is generated from the Go API types by [crd-ref-docs](https://github.com/elastic/crd-ref-docs). It lists every field; the topic guides show examples and explain behavior.

The API is still `v1alpha1`, so fields may change while the operator is under active development.

{{ range $groupVersions }}
{{ template "gvDetails" . }}
{{ end }}

{{- end -}}
