//go:build e2e
// +build e2e

package e2e

import (
	"fmt"
	"time"

	. "github.com/onsi/ginkgo/v2"
	. "github.com/onsi/gomega"
)

// backupCleanupFinalizer is the finalizer the operator stamps onto a Backup with
// reclaimPolicy: Delete. It must match the constant used by the operator
// (internal/controller.backupFinalizer).
const backupCleanupFinalizer = "mysql.cnmsql.co/cleanup-backup-files"

// This spec exercises the opt-in Backup reclaim policy: a Backup with
// spec.reclaimPolicy: Delete has the operator stamp the cleanup finalizer and,
// on deletion, remove its archive (backup.xbstream + metadata.json) from the
// object store before releasing the finalizer. It also asserts the default
// (Retain) behavior leaves the archive in place.
var _ = Describe("Backup cleanup finalizer", Ordered, Label("flavor"), func() {
	const (
		finCluster   = "bkp-fin-src"
		finalizedBkp = "finalized-backup"
		retainedBkp  = "retained-backup"
	)

	var ns, prevNS string

	BeforeAll(func() {
		prevNS = testNamespace
		ns = createTestNamespace("backup-finalizer")

		setupMinio()
		DeferCleanup(teardownMinio)
		setupMC()
		DeferCleanup(teardownMC)

		By("creating the source cluster that archives to object storage")
		applyManifest(finCluster, archivingClusterManifest(finCluster))
		DeferCleanup(func() {
			deleteManifest(finCluster, archivingClusterManifest(finCluster))
		})
		expectClusterReady(finCluster, 1, 20*time.Minute)
	})

	It("removes the archive from the object store when a Delete-policy Backup is deleted", func() {
		By("creating a Backup with reclaimPolicy: Delete")
		applyManifest(finalizedBkp, backupManifestReclaimDelete(finalizedBkp, finCluster))

		By("verifying the operator stamps the cleanup finalizer")
		Eventually(func(g Gomega) {
			finalizers, err := kubectl("get", "backup", finalizedBkp, "-n", testNamespace,
				"-o", "jsonpath={.metadata.finalizers[*]}")
			g.Expect(err).NotTo(HaveOccurred())
			g.Expect(finalizers).To(ContainSubstring(backupCleanupFinalizer),
				"operator should stamp the cleanup finalizer for reclaimPolicy: Delete")
		}, e2eTimeout(1*time.Minute), 5*time.Second).Should(Succeed())

		By("waiting for the backup to complete")
		Eventually(func(g Gomega) {
			phase, err := kubectl("get", "backup", finalizedBkp, "-n", testNamespace,
				"-o", "jsonpath={.status.phase}")
			g.Expect(err).NotTo(HaveOccurred())
			g.Expect(phase).NotTo(Equal("failed"), "backup failed")
			g.Expect(phase).To(Equal("completed"), "backup not completed yet")
		}, e2eTimeout(8*time.Minute), 5*time.Second).Should(Succeed())

		id, err := kubectl("get", "backup", finalizedBkp, "-n", testNamespace,
			"-o", "jsonpath={.status.backupId}")
		Expect(err).NotTo(HaveOccurred())
		Expect(id).NotTo(BeEmpty(), "backup has no backupId")

		archiveKey := backupObjectKey(finCluster, finalizedBkp, id, "backup.xbstream")
		metadataKey := backupObjectKey(finCluster, finalizedBkp, id, "metadata.json")

		By("confirming the archive exists in the store before deletion")
		Expect(mcObjectExists(archiveKey)).To(BeTrue(), "archive should exist before deletion")
		Expect(mcObjectExists(metadataKey)).To(BeTrue(), "metadata should exist before deletion")

		By("deleting the Backup object")
		// The finalizer blocks removal until the operator cleans the store, so do
		// not wait synchronously; poll for the object and the artifacts to go away.
		_, err = kubectl("delete", "backup", finalizedBkp, "-n", testNamespace, "--wait=false")
		Expect(err).NotTo(HaveOccurred())

		By("verifying the archive and metadata are removed from the store")
		Eventually(func(g Gomega) {
			g.Expect(mcObjectExists(archiveKey)).To(BeFalse(), "archive should be deleted")
			g.Expect(mcObjectExists(metadataKey)).To(BeFalse(), "metadata should be deleted")
		}, e2eTimeout(3*time.Minute), 5*time.Second).Should(Succeed())

		By("verifying the finalizer is released and the Backup object is gone")
		Eventually(func(g Gomega) {
			_, err := kubectl("get", "backup", finalizedBkp, "-n", testNamespace)
			g.Expect(err).To(HaveOccurred(), "Backup object should be deleted once the finalizer is released")
		}, e2eTimeout(2*time.Minute), 5*time.Second).Should(Succeed())
	})

	It("propagates the cleanup finalizer to Backups generated by a ScheduledBackup", func() {
		const scheduleName = "bkp-fin-sched"
		selector := "mysql.cnmsql.co/scheduled-backup=" + scheduleName

		By("creating a ScheduledBackup with reclaimPolicy: Delete")
		// immediate fires one backup now; the daily cron slot won't fire during the
		// test, so exactly one generated Backup is exercised.
		applyManifest(scheduleName, scheduledBackupCleanupManifest(scheduleName, finCluster, "0 0 2 * * *"))
		DeferCleanup(func() {
			deleteManifest(scheduleName, scheduledBackupCleanupManifest(scheduleName, finCluster, "0 0 2 * * *"))
		})

		By("waiting for the immediate generated Backup to appear")
		var genBackup string
		Eventually(func(g Gomega) {
			names := backupNamesWithLabel(g, selector)
			g.Expect(names).NotTo(BeEmpty(), "no backup generated by the ScheduledBackup yet")
			genBackup = names[0]
		}, e2eTimeout(2*time.Minute), 5*time.Second).Should(Succeed())

		By("verifying the generated Backup inherits reclaimPolicy and gets the cleanup finalizer")
		Eventually(func(g Gomega) {
			finalizers, err := kubectl("get", "backup", genBackup, "-n", testNamespace,
				"-o", "jsonpath={.metadata.finalizers[*]}")
			g.Expect(err).NotTo(HaveOccurred())
			g.Expect(finalizers).To(ContainSubstring(backupCleanupFinalizer),
				"generated Backup should inherit reclaimPolicy: Delete and get the finalizer")
		}, e2eTimeout(1*time.Minute), 5*time.Second).Should(Succeed())

		By("waiting for the generated Backup to complete")
		Eventually(func(g Gomega) {
			phase, err := kubectl("get", "backup", genBackup, "-n", testNamespace,
				"-o", "jsonpath={.status.phase}")
			g.Expect(err).NotTo(HaveOccurred())
			g.Expect(phase).NotTo(Equal("failed"), "generated backup failed")
			g.Expect(phase).To(Equal("completed"), "generated backup not completed yet")
		}, e2eTimeout(8*time.Minute), 5*time.Second).Should(Succeed())

		id, err := kubectl("get", "backup", genBackup, "-n", testNamespace,
			"-o", "jsonpath={.status.backupId}")
		Expect(err).NotTo(HaveOccurred())
		Expect(id).NotTo(BeEmpty(), "generated backup has no backupId")
		archiveKey := backupObjectKey(finCluster, genBackup, id, "backup.xbstream")
		Expect(mcObjectExists(archiveKey)).To(BeTrue(), "archive should exist before deletion")

		By("deleting the generated Backup")
		_, err = kubectl("delete", "backup", genBackup, "-n", testNamespace, "--wait=false")
		Expect(err).NotTo(HaveOccurred())

		By("verifying the finalizer cleaned the archive from the store")
		Eventually(func(g Gomega) {
			g.Expect(mcObjectExists(archiveKey)).To(BeFalse(), "archive should be deleted by the finalizer")
		}, e2eTimeout(3*time.Minute), 5*time.Second).Should(Succeed())
	})

	It("leaves the archive in place when a Backup without the finalizer is deleted", func() {
		By("creating a Backup without any cleanup finalizer")
		applyManifest(retainedBkp, backupManifest(retainedBkp, finCluster))

		By("waiting for the backup to complete")
		Eventually(func(g Gomega) {
			phase, err := kubectl("get", "backup", retainedBkp, "-n", testNamespace,
				"-o", "jsonpath={.status.phase}")
			g.Expect(err).NotTo(HaveOccurred())
			g.Expect(phase).NotTo(Equal("failed"), "backup failed")
			g.Expect(phase).To(Equal("completed"), "backup not completed yet")
		}, e2eTimeout(8*time.Minute), 5*time.Second).Should(Succeed())

		id, err := kubectl("get", "backup", retainedBkp, "-n", testNamespace,
			"-o", "jsonpath={.status.backupId}")
		Expect(err).NotTo(HaveOccurred())
		Expect(id).NotTo(BeEmpty(), "backup has no backupId")

		archiveKey := backupObjectKey(finCluster, retainedBkp, id, "backup.xbstream")

		By("deleting the Backup object")
		_, err = kubectl("delete", "backup", retainedBkp, "-n", testNamespace)
		Expect(err).NotTo(HaveOccurred())

		By("verifying the archive is retained in the store")
		// Give the operator time to (not) act, then assert the archive still exists.
		Consistently(func(g Gomega) {
			g.Expect(mcObjectExists(archiveKey)).To(BeTrue(), "archive should be retained without the finalizer")
		}, 30*time.Second, 5*time.Second).Should(Succeed())
	})

	AfterAll(func() {
		deleteTestNamespace(ns, prevNS)
	})
})

// backupObjectKey builds the mc-addressed object key for one of a backup's
// archive-directory objects. The store uses no path prefix in these specs, so
// the layout is <bucket>/<cluster>/<backup>/<backupId>/<object>.
func backupObjectKey(cluster, backup, backupID, object string) string {
	return fmt.Sprintf("local/%s/%s/%s/%s/%s", minioBucket, cluster, backup, backupID, object)
}

func scheduledBackupCleanupManifest(name, cluster, schedule string) string {
	return fmt.Sprintf(`apiVersion: mysql.cnmsql.co/v1alpha1
kind: ScheduledBackup
metadata:
  name: %s
  namespace: %s
spec:
  schedule: "%s"
  immediate: true
  reclaimPolicy: Delete
  cluster:
    name: %s
  method: xtrabackup
`, name, testNamespace, schedule, cluster)
}

func backupManifestReclaimDelete(name, cluster string) string {
	return fmt.Sprintf(`apiVersion: mysql.cnmsql.co/v1alpha1
kind: Backup
metadata:
  name: %s
  namespace: %s
spec:
  cluster:
    name: %s
  method: xtrabackup
  reclaimPolicy: Delete
`, name, testNamespace, cluster)
}
